### ISSUE TITLE
Weekly To Do List - 24/11/2020

### ISSUE THREAD

**Issue by walt123uk** [walt123uk/blog-laravel#3]
- [x] WYSIWYG Editor
- [x] Install and implement Laravel Media Library (Can attach images to posts)

**Route**

Amber
- [x] Route Group (Post routes grouped and middleware auth applied)
- [x] Group Options 

**Controller**

Amber
- [x] Middleware (Applied to PostController)

**Blade**

Amber
- [x] Form (Included in the create and edit views and register, login etc)

**Comment by j-dohnalek** [comment]
Tim, great suggestions. However, you just showing what you plan to achieve. The plan is too high level. You must break it down. What will you implement in order to learn ...? Why do you think you should implement it using ...? I will let you off this week, but next weeks work must show more details.
